apiVersion: v1
data:
  authorized_keys: >-
    c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUpTczV1eFpMQzFnVk1QVkNVMGtsaUU3Z0g1WnBiNkNPZEFpaURyNkZ2d2ogbWFya2hzdUBaYW5lSHN1Cg==
kind: Secret
metadata:
  creationTimestamp: '2026-03-14T13:29:29Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:authorized_keys: {}
        f:type: {}
      manager: kubectl-create
      operation: Update
      time: '2026-03-14T13:29:29Z'
  name: sftp-key
  namespace: sftp
  resourceVersion: '16438'
  uid: 0782a7d6-528a-4aea-a708-d6ccfda7e813
type: Opaque
